### PR TITLE
You can now pip install twolde

### PR DESCRIPTION
**Pull request by eartle**
- also removed some more things about mac
- also now put the config in a hidden user home dir “~/.twolde/config.ini”

### CODE REVIEW

**Comment by eartle** [comment]
I'm going to comment on my own pull request, but the README needs updating for instructions on how to pip install. Should just need to `pip install <github_url>`.

**Comment by hugovk** [comment]
:+1:

**Comment by hugovk** [comment]
Pip working and tested like this:

```
pip install git+git://github.com/eartle/twolde.git
```

Then runnable like:

```
twolde install
...
twolde run
...
```

**Comment by hugovk** [comment]
Next step: release it on PyPI so you can just `pip install twolde`.

**Comment by eartle** [comment]
I just updated the README and realised it's now a bit odd to `pip install` and then `twolde install`. Maybe the Twolde command should be `auth` or something else as installing twice seems a bit strange.

**Comment by hugovk** [comment]
Yeah, `auth` makes sense.

It was more instally with the since-removed Mac stuff. It's definitely more authy now.

**Pull request merged**
